language: python

addons:
  apt:
    packages:
    - libbz2-dev
    - libhdf5-dev
    - liblzo2-dev

python:
  - "3.6"

virtualenv:
  system_site_packages: false

# command to install dependencies
install:
  - pip install numpy 
  - pip install -r requirements.txt
  - pip install coveralls

# running tests
script:
  - nosetests --with-coverage --cover-package=pymicro

after_success:
  - coveralls
